spring.application.name=servicediscovery
server.port=8761

# Make config server optional (fail-safe mode)
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.username=admin
spring.cloud.config.password=admin
spring.cloud.config.fail-fast=false

# Eureka Server Configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true
eureka.server.eviction-interval-timer-in-ms=5000

# Dashboard
eureka.dashboard.enabled=true

# Instance settings
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
